spring:
  application:
    name: spring-cloud-dubbo-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: mapleVM:8848
dubbo:
  registry:
    address: spring-cloud://mapleVM:8848
  protocol:
    name: dubbo
    port: 20080
server:
  port: 11111
