spring:
  application:
    name: dubbo-nacos-consumer
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://mapleVM:8848
  protocol:
    name: dubbo
    port: 20080
server:
  port: 11112
nacos:
  discovery:
    server-addr: mapleVM:8848